### ISSUE TITLE
How do I get the information about Power Node (activeProfiles ......)?

### ISSUE THREAD

**Issue by shaorui0** [intel/kubernetes-power-manager#12]
How do I get this information?
https://github.com/intel/kubernetes-power-manager#example-5
```
activeProfiles:
    performance-example-node: true
  activeWorkloads:
  - cores:
    - 2
    - 3
    - 8
    - 9
    name: performance-example-node-workload
  nodeName: example-node
  powerContainers:
  - exclusiveCpus:
  ......
```
