### ISSUE TITLE
Error: C-state C0 does not exist on this system

### ISSUE THREAD

**Issue by shaorui0** [intel/kubernetes-power-manager#17]
Hi, 
I followed the instruction to deploy the kubernetes-power-manager and then I applied an example-cstates.yaml. C1/C6 can be set correctly but C0 cannot. (C0 can be set correctly by other means on this server)

Error log:
```
1.6630839796250973e+09  INFO    controllers.CState      Reconciling C-states    {"cStates": "default/master"}
1.6630839796253767e+09  ERROR   controllers.CState      CStates validation failed       {"cStates": "default/master", "error": "12 errors occurred:\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\t* C-State C0 is invalid on node master\n\n"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
1.663083979998775e+09   ERROR   Reconciler error        {"controller": "cstates", "controllerGroup": "power.intel.com", "controllerKind": "CStates", "cStates": {"name":"master","namespace":"default"}, "namespace": "default", "name": "master", "reconcileID": "2e85769e-4056-4a62-8391-6e88f0a36025", "error": "2 errors occurred:\n\t* C-state C0 does not exist on this system\n\t* C-state C0 does not exist on this system\n\n"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```
c-state config
```yaml
apiVersion: power.intel.com/v1
kind: CStates
metadata:
  # Replace <NODE_NAME> with the name of the node to configure the C-States on that node
  name: master
spec:
  sharedPoolCStates:
    C0: true
  exclusivePoolCStates:
    performance:
      C0: false
  individualCoreCStates:
    "24":
      C0: true

```

$ kubectl get nodes
NAME     STATUS   ROLES                  AGE   VERSION
master   Ready    control-plane,master   75d   v1.20.2
