### ISSUE TITLE
Old version of power-node-agent image

### ISSUE THREAD

**Issue by dkasanic** [intel/kubernetes-power-manager#32]
The image intel/power-operator:v2.2.0 in dockerhub has old version of node-agent-ds image defined in file `/power-manifests/power-node-agent-ds.yaml`:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: power-node-agent
  namespace: intel-power
spec:
  selector:
    matchLabels:
      name: power-node-agent-pod
  template:
    metadata:
      namespace: intel-power
      labels:
        name: power-node-agent-pod
    spec:
      serviceAccountName: intel-power-node-agent
      containers:
        - image: intel/power-node-agent:v2.1.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          name: power-node-agent
          args: [ "--zap-log-level","3" ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /sys/devices/system/cpu
              name: cpusetup
            - mountPath: /sys/fs
              name: cgroup
              readOnly: true
            - mountPath: /var/lib/kubelet/pod-resources/
              name: kubesock
              readOnly: true
      volumes:
        - name: cpusetup
          hostPath:
            path: /sys/devices/system/cpu
        - name: cgroup
          hostPath:
            path: /sys/fs
        - name: kubesock
          hostPath:
            path: /var/lib/kubelet/pod-resources
```
Therefore when powerconfig is applied, controller-manager will spawn node-agent-ds with old version of node-agent image (v2.1.0 instead of v2.2.0)
